export class Groundwater {
    constructor (
        public id: number,
        public tubewellNo: number,
        public location: string,
        public aquiferMaterial: string,
        public latitude: number,
        public totalDrillDepth: number,
        public longtitude: number,
        public housingLength: number,
        public elevation: number,
        public screenLength: number,
        public typeOfTubewell: string,
        public typeOfScreen: string,
        public tubewellHousingPipeSize: number,
        public pumpingDischarge: number,
        public tubewellScreenAndCasingPipeSize: number,
        public drawdown: number,
        public staticWaterLevel: number,
        public aquiferStorageCoefficient: number,
        public aquiferTransmissivity: number,
        public brandOfPump: string,
        public power: number,
        public sizeOfPumpHouse: number,
        public head: number,
        public heightOfOverheadTank: number,
        public pumpDischarge: number,
        public volumeOfOverheadTank: number,
        public efficiencyOfMotor: number,
        public efficiencyOfPump: number,
        public pumpLoweringDepth: number,
        public columnPipeSize: number,
        public columnType: string,
        public lengthOf11kvHTTransmissionLine: number,
        public transformerCapacity: number,
        public transmissionLine: number,
        public controlPanel: number,
        public noOfPoles: number,
        public volatageStabilizer: number,
        public typeOfDistributionSystem: string,
        public noOfOutlets: number,
        public lengthOfOpenChannel: number,
        public sizeOfAlphaAlphaValve: number,
        public pipeMaterial: string,
        public lengthOfPipe: number,
        public noOfSurgeRaiser: number,
        ) {}
}
